apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: superset-postgresql-statefulset
  namespace: superset
  labels:
    app: &app postgresql
spec:
  replicas: 1
  serviceName: superset-postgresql-headless
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: *app
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: *app
    spec:
      containers:
      - name: superset-postgresql-container
        image: bitnami/postgresql:16.1.0
        env:
        - name: POSTGRESQL_DATABASE
          value: superset
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: superset-postgresql-secret
              key: password
        - name: POSTGRESQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: superset-postgresql-secret
              key: username
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          exec: &healthcheck
            command:
            - /bin/sh
            - -c
            - pg_isready -U $POSTGRESQL_USERNAME
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        ports:
        - name: tcp-port
          protocol: TCP
          containerPort: 5432
        readinessProbe:
          failureThreshold: 3
          exec: *healthcheck
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits: {}
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1001
        startupProbe:
          exec: *healthcheck
          failureThreshold: 30
          periodSeconds: 10  
        volumeMounts:
        - mountPath: /data/pgdata:/bitnami/postgresql
          name: superset-postgresql-volume
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: "OnRootMismatch"
  volumeClaimTemplates:
  - metadata:
      name: superset-postgresql-volume
      namespace: superset
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
