apiVersion: v1
kind: Service
metadata:
  name: superset-postgresql-headless
  namespace: superset
  labels:
    app: &app postgresql
spec:
  clusterIP: None
  ports:
  - name: tcp-port
    port: 5432
    protocol: TCP
    targetPort: tcp-port
  selector:
    app: *app
