apiVersion: v1
kind: Service
metadata:
  name: superset-redis-headless
  namespace: superset
  labels:
    app: &app redis
spec:
  clusterIP: None
  ports:
  - name: tcp-port
    protocol: TCP
    port: 6379
    targetPort: tcp-port
  selector:
    app: *app
